/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Palm.glb -o src/components/Palm.jsx -r public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useControls } from 'leva'

export function Palm(props) {
  const { nodes, materials } = useGLTF('/models/Palm.glb')

  // Leva controls for position
  const { position } = useControls('Palm', {
    position: { value: [0.5, -0.4, -0.5], step: 0.1 }
  })

  return (
    <group {...props} dispose={null} position={position} scale={[0.8, 0.8, 0.8]}>
      <mesh geometry={nodes.Environment_PalmTree_3.geometry} material={materials.Atlas} scale={100} castShadow />
    </group>
  )
}

useGLTF.preload('/models/Palm.glb')
